config/routes.rb
CoolInnovations::Application.routes.draw do

  resources :stations do
    post :update_station, :on => :collection
    get :index_floor, :on => :collection
  end

  resources :attachments

  resources :part_process_categories do
    post :update_part_process_category, :on => :collection
    post :set_sort_priority, :on => :collection
  end

  resources :hardware_categories do
    post :update_hardware_category, :on => :collection
    post :set_sort_priority, :on => :collection
  end

  resources :sample_lines

  resources :comments

  resources :shipping_methods do
    get :search, :on => :collection
    post :update_shipping_method, :on => :collection
  end

  resources :order_lines do
    post :set_process_status, :on => :collection
    post :update_order_line, :on => :collection
    post :update_order_lines, :on => :collection
    post :reset_order_line_status, :on => :collection
    post :assign_user, :on => :collection
    post :update_order_line_process_status, :on => :collection
    get :accordion_details, :on => :member
  end

  resources :orders do
    match :shipped, :on => :collection, :action => :index, :display => "shipped"
    match :update_search_dropdowns, :on => :collection
  end

  resources :parts do
    get  :search, :on => :collection
    post :update_part, :on => :collection
    post :set_required_process_priority, :on => :member
    get :accordion_details, :on => :member
  end

  resources :part_processes do
    post :part_processes, :on => :collection
    post :set_order_line_priority, :on => :member
    post :reset_order_line_priority, :on => :member
    post :update_part_process, :on => :collection
    get :accordion_details, :on => :member
  end

  resources :hardwares do
    get :search, :on => :collection
    post :update_hardware, :on => :collection
    get :accordion_details, :on => :member
  end

  resources :users do
    post :update_user, :on => :collection
    post :set_process_priority, :on => :member
  end
  resources :sessions

  resources :clients do
    get :search, :on => :collection
    post :update_client, :on => :collection
    get :accordion_details, :on => :member
  end

  root to: "sessions#index"
  get 'login' => "sessions#new"
  get 'logout' => "sessions#destroy"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :message, :sample_lines_attributes, :customer_name, :contact_name, :address, :shipping_account_info, :comment, :parent_id
  belongs_to :user


  has_many :sample_lines, :dependent => :destroy
  has_many :parts, :through => :sample_lines

  accepts_nested_attributes_for :sample_lines

  has_ancestry

  def self.homeOrders
    order_lines = OrderLine.joins(:order => :client).includes(:order => :client).includes(:part).joins(:part)
    order_lines = order_lines.where{(status != "shipped") & (color != "f-white") & (color != "white") & (color != "d-white")}
    order_lines = order_lines.order('color ASC, ship_date ASC, clients.name ASC')
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.order("created_at desc").where(:ancestry => nil).page(params[:page] || 1).per_page(params[:per_page] || 30)
    # @order_lines = OrderLine.where{(status != "shipped") & (color != "f-white") & (color != "white") & (color != "d-white") }.order("color asc, ship_date asc")
    @order_lines = Comment.homeOrders
    if @comments.length > 0
      last_id = @comments[0].id
    end

    if cookies["latest_comment"] == nil
      @latest_comment_id = last_id
    else
      @comments.each do |comment|
        if (comment.id == cookies["latest_comment"].to_i  )
          @latest_comment_id = comment.id
          break
        end
      end
    end

    cookies["latest_comment"] = last_id



    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new(:parent_id => params[:parent_id])

    respond_to do |format|
      format.html do
        render :layout => false if params[:no_layout]
      end
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html do
        render :layout => false if params[:no_layout]
      end
      format.json { render json: @comment }
    end
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.js
      else
        format.html { render action: "new" }
        format.js
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.js
      else
        format.html { render action: "edit" }
        format.js
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def nested_comments(comments)
    comments.map do |comment, sub_comments|
      render(comment) + 
        content_tag(:div, render(comment.children.order(:created_at)), :class => "nested_comments")
    end.join.html_safe
  end
end

app/views/comments/_comment.html.erb
<% if @latest_comment_id == comment.id %>
    <% @is_seen = true %>
<% end %>
<div class="comment-container <% if @is_seen == false%>new<%end%>" data-id="<%= comment.id %>">
  <div class="row">
    <!--<div class="span1">
      <% if comment.user.try(:avatar?) %>
        <%= image_tag comment.user.avatar.url(:thumb) %>
      <% else %>
        <%= image_tag "silhouette.png" %>
      <% end %>
      <span class="actions">
        <% extra_param = "" %>
        <% if comment.sample_lines.length >0 %>
          <% extra_param = "&sample=true" %>
        <% end %>
        <% if comment.user.try(:id) == current_user.id %>
          <%= link_to edit_comment_path(comment)+"?no_layout=1"+extra_param, :class => 'edit modal-trigger', :title => 'Edit' do%>
            <i class="icon-edit"></i>
          <% end %>
        <% end %>
        <% if comment.user.try(:id) == current_user.id or current_user.admin?  %>
          <%= link_to comment, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'delete', :title => 'Delete' do%>
            <i class="icon-trash" alt="delete"></i>
          <% end %>
        <% end %>
        <%= link_to new_comment_path(:no_layout => 1, :parent_id => comment.id), :class => 'reply modal-trigger', :title => 'Reply' do%>
          <i class="icon-comments-alt"></i>
        <% end if comment.ancestry.nil? %>
      </span>
    </div>-->
    <div class="span7 comment-details">
      <div class="username"><%= comment.user.try(:name) %></div>
      <div class="date"><em><%= comment.created_at.to_formatted_s(:long) %></em></div>
      <div class="message">
        <% if comment.sample_lines.length >0 %>
          Sample for: <strong><%= comment.customer_name %></strong>
          <% if comment.contact_name? %><br />Contact Name:<strong><%= comment.contact_name %></strong><% end %>
          <table class="table table-bordered table-condensed table-striped mtx">
            <thead>
              <tr>
                <th>Part #</th>
                <th>New Part #</th>
                <th>Quantity</th>
              </tr>
            </thead>
            <tbody>
              <% comment.sample_lines.each do |sample_line| %>
                <tr>
                  <td class="comment"><% if sample_line.part_id? %><%= sample_line.part.name %><% end %></td>
                  <td class="comment"><%= sample_line.new_part_number %></td>
                  <td><%= sample_line.quantity %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <% if comment.address? or comment.shipping_account_info? or comment.comment? %>
            <table class="table table-bordered table-condensed">
              <% if comment.address? %>
                <tr>
                  <td class="small"><strong>Address:</strong></td>
                  <td><%= simple_format comment.address %></td>
                </tr>
              <% end %>
              <% if comment.shipping_account_info? %>
                <tr>
                  <td><strong>Shipping Info:</strong></td>
                  <td><%= simple_format comment.shipping_account_info %></td>
                </tr>
              <% end %>
              <% if comment.comment? %>
                <tr>
                  <td><strong>Comment:</strong></td>
                  <td><%= simple_format comment.comment %></td>
                </tr>
              <% end %>
            </table>
          <% end %>
        <% else %>
          <%= simple_format comment.message %>
        <% end %>
      </div>
    </div>
    <div class="comment-actions span6">
      <% extra_param = "" %>
      <% if comment.sample_lines.length >0 %>
          <% extra_param = "&sample=true" %>
      <% end %>
      <% if comment.user.try(:id) == current_user.id %>
          <%= link_to edit_comment_path(comment)+"?no_layout=1"+extra_param, :class => 'edit modal-trigger', :title => 'Edit' do%>
              <i class="icon-edit"></i>
          <% end %>
      <% end %>
      <% if comment.user.try(:id) == current_user.id or current_user.admin?  %>
          <%= link_to comment, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'delete', :title => 'Delete' do%>
              <i class="icon-trash" alt="delete"></i>
          <% end %>
      <% end %>
      <%= link_to new_comment_path(:no_layout => 1, :parent_id => comment.id), :class => 'reply modal-trigger', :title => 'Reply' do%>
          <i class="icon-comments-alt"></i>
      <% end if comment.ancestry.nil? %>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%if  params["sample"] %>
    <% form_style = "sample-form" %>
<% else %>
    <% form_style = "" %>
<% end %>

<%= simple_form_for(@comment, :remote => true, :html => { :class => 'form form-horizontal '+form_style }) do |f| %>
  <%= f.error_notification %>
  <div class="modal-body">
    <%= f.input :parent_id, :as => :hidden if @comment.parent_id.present? %>
  <%if  params["sample"] %>
    <%= f.input :customer_name %>
    <%= f.input :contact_name %>
    <%= f.input :address %>
    <%= f.input :shipping_account_info %>
    <%= f.input :comment %>
    <table class="table table-condensed sample-lines">
      <thead>
          <tr>
            <th>Existing Part</th>
            <th>New Part</th>
            <th>Qty</th>
            <th></th>
          </tr>
      </thead>
      <tbody id="sample_lines">
          <%= f.simple_fields_for :sample_lines do |sample_line| %>
              <%= render 'sample_line_fields', :f => sample_line %>
          <% end %>
          <tr>
            <td colspan="3">
              <div class="links">
                <%= link_to_add_association 'Add Line', f, :sample_lines, :class => 'btn',
                                            :"data-association-insertion-node" => '#sample_lines',
                                            :"data-association-insertion-method" => "prepend"
                %>
              </div>
            </td>
          </tr>
      </tbody>
    </table>
  <% else %>
    <%= f.input :message %>
  <% end %>
  </div>

  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Cancel</a>
    <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/comments/_sample_line_fields.html.erb
<tr class="nested-fields">
  <td><%= f.association :part, :label =>false, :collection => Part.order(:part_number).all, :input_html => {:"data-placeholder" => "Part #", :class => "span2"} %></td>
  <td><%= f.input :new_part_number, :label =>false ,:input_html => {:class => "span1"} %></td>
  <td><%= f.input :quantity, :label =>false,:input_html => {:class => "span1"} %></td>
  <td>
    <%= link_to_remove_association  f, :class => "btn btn-small btn-danger", :title => "Remove Line" do%>
        <i class="icon-trash" alt="edit"></i>
    <% end %>
  </td>
</tr>

app/views/comments/edit.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">×</button>
  <h3>Edit Comment</h3>
</div>

<%= render 'form' %>

app/views/comments/index.html.erb
<% @is_seen = false %>
<div class="row">
  <div class="span9 scroll">
    <h2>Upcoming Orders</h2>
    <table class="table table-bordered table-condensed">
      <thead>
        <th>Customer</th>
        <th>P/O #</th>
        <th>Part #</th>
        <th>Qty</th>
        <th>Comment</th>
        <th>Breakdown</th>
        <th>PU Time</th>
      </thead>
      <tbody>
        <% @order_lines.each do |order_line| %>
            <tr class="<%= order_line.color %>">
              <td>
                <% if order_line.order.client %>
                    <%= order_line.order.client.name %>
                <% end %>
              </td>
              <td><%= order_line.order.purchase_order %></td>
              <td>
                <% if order_line.part %>
                    <%= order_line.part.name.upcase %>
                <% end %>
              </td>
              <td><%= number_with_delimiter(order_line.quantity) %></td>
              <td class="editable medium" data-headers="/order_lines/update_order_line"  id="comment-<%= order_line.id%>" data-content="<%= order_line.comment %>"><%= order_line.comment %></td>
              <td class="editable medium" data-headers="/order_lines/update_order_line"  id="breakdown-<%= order_line.id%>" data-content="<%= order_line.breakdown %>"><%= order_line.breakdown %></td>
              <td class="editable pickuptime" data-headers="/order_lines/update_order_line" id="pickuptime-<%= order_line.id%>"><%= order_line.pickuptime %></td>
            </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'View All', orders_path%>
  </div>
  <div class="span3">
    <h3>Comments <%= link_to 'Sample', "/comments/new?sample=true&no_layout=1", :class => 'btn btn-small btn-primary pull-right mrx mbxx modal-trigger'%> <%= link_to 'Comment', "/comments/new?no_layout=1", :class => 'btn btn-small btn-primary pull-right mrx mbxx modal-trigger'%></h3>
    <% if @comments.length > 0 %>
        <%= nested_comments @comments %>
    <% else %>
        There are no comments
    <% end %>
  </div>
</div>

app/views/comments/new.html.erb
<% if params[:sample] %>
    <% title = "New Sample" %>
<% elsif params[:parent_id] %>
    <% title = "Reply to Comment" %>
<% else %>
    <% title = "New Comment" %>
<% end %>
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">×</button>
  <h3><%= title %></h3>
</div>

<%= render 'form' %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Message:</b>
  <%= @comment.message %>
</p>

<p>
  <b>User:</b>
  <%= @comment.user %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>