config/routes.rb
CoolInnovations::Application.routes.draw do

  resources :stations do
    post :update_station, :on => :collection
    get :index_floor, :on => :collection
  end

  resources :attachments

  resources :part_process_categories do
    post :update_part_process_category, :on => :collection
    post :set_sort_priority, :on => :collection
  end

  resources :hardware_categories do
    post :update_hardware_category, :on => :collection
    post :set_sort_priority, :on => :collection
  end

  resources :sample_lines

  resources :comments

  resources :shipping_methods do
    get :search, :on => :collection
    post :update_shipping_method, :on => :collection
  end

  resources :order_lines do
    post :set_process_status, :on => :collection
    post :update_order_line, :on => :collection
    post :update_order_lines, :on => :collection
    post :reset_order_line_status, :on => :collection
    post :assign_user, :on => :collection
    post :update_order_line_process_status, :on => :collection
    get :accordion_details, :on => :member
  end

  resources :orders do
    match :shipped, :on => :collection, :action => :index, :display => "shipped"
    match :update_search_dropdowns, :on => :collection
  end

  resources :parts do
    get  :search, :on => :collection
    post :update_part, :on => :collection
    post :set_required_process_priority, :on => :member
    get :accordion_details, :on => :member
  end

  resources :part_processes do
    post :part_processes, :on => :collection
    post :set_order_line_priority, :on => :member
    post :reset_order_line_priority, :on => :member
    post :update_part_process, :on => :collection
    get :accordion_details, :on => :member
  end

  resources :hardwares do
    get :search, :on => :collection
    post :update_hardware, :on => :collection
    get :accordion_details, :on => :member
  end

  resources :users do
    post :update_user, :on => :collection
    post :set_process_priority, :on => :member
  end
  resources :sessions

  resources :clients do
    get :search, :on => :collection
    post :update_client, :on => :collection
    get :accordion_details, :on => :member
  end

  root to: "sessions#index"
  get 'login' => "sessions#new"
  get 'logout' => "sessions#destroy"

end

app/models/sample_line.rb
class SampleLine < ActiveRecord::Base
  attr_accessible :comment_id, :part_id, :quantity, :new_part_number

  validates_presence_of  :quantity

  belongs_to :comment
  belongs_to :part
end

app/controllers/sample_lines_controller.rb
class SampleLinesController < ApplicationController
  # GET /sample_lines
  # GET /sample_lines.json
  def index
    @sample_lines = SampleLine.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sample_lines }
    end
  end

  # GET /sample_lines/1
  # GET /sample_lines/1.json
  def show
    @sample_line = SampleLine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sample_line }
    end
  end

  # GET /sample_lines/new
  # GET /sample_lines/new.json
  def new
    @sample_line = SampleLine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sample_line }
    end
  end

  # GET /sample_lines/1/edit
  def edit
    @sample_line = SampleLine.find(params[:id])
  end

  # POST /sample_lines
  # POST /sample_lines.json
  def create
    @sample_line = SampleLine.new(params[:sample_line])

    respond_to do |format|
      if @sample_line.save
        format.html { redirect_to @sample_line, notice: 'Sample line was successfully created.' }
        format.json { render json: @sample_line, status: :created, location: @sample_line }
      else
        format.html { render action: "new" }
        format.json { render json: @sample_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sample_lines/1
  # PUT /sample_lines/1.json
  def update
    @sample_line = SampleLine.find(params[:id])

    respond_to do |format|
      if @sample_line.update_attributes(params[:sample_line])
        format.html { redirect_to @sample_line, notice: 'Sample line was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sample_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sample_lines/1
  # DELETE /sample_lines/1.json
  def destroy
    @sample_line = SampleLine.find(params[:id])
    @sample_line.destroy

    respond_to do |format|
      format.html { redirect_to sample_lines_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sample_lines_helper.rb
module SampleLinesHelper
end

app/views/sample_lines/_form.html.erb
<%= simple_form_for(@sample_line, :html => { :class => 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :comment_id %>
    <%= f.input :part_id %>
    <%= f.input :quantity %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to 'Cancel', sample_lines_path, :class => 'btn' %>
  </div>
<% end %>

app/views/sample_lines/edit.html.erb
<h1>Editing sample_line</h1>

<%= render 'form' %>

<%= link_to 'Show', @sample_line %> |
<%= link_to 'Back', sample_lines_path %>

app/views/sample_lines/index.html.erb
<h1>Listing sample_lines</h1>

<table class="table table-striped">
  <tr>
    <th>Comment</th>
    <th>Part</th>
    <th>Quantity</th>
    <th>Actions</th>
  </tr>

<% @sample_lines.each do |sample_line| %>
  <tr>
    <td><%= sample_line.comment_id %></td>
    <td><%= sample_line.part_id %></td>
    <td><%= sample_line.quantity %></td>
    <td>
      <%= link_to 'Show', sample_line, :class => 'btn btn-mini' %>
      <%= link_to 'Edit', edit_sample_line_path(sample_line), :class => 'btn btn-mini' %>
      <%= link_to 'Destroy', sample_line, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sample line', new_sample_line_path, :class => 'btn btn-primary' %>

app/views/sample_lines/new.html.erb
<h1>New sample_line</h1>

<%= render 'form' %>

<%= link_to 'Back', sample_lines_path %>

app/views/sample_lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Comment:</b>
  <%= @sample_line.comment_id %>
</p>

<p>
  <b>Part:</b>
  <%= @sample_line.part_id %>
</p>

<p>
  <b>Quantity:</b>
  <%= @sample_line.quantity %>
</p>


<%= link_to 'Edit', edit_sample_line_path(@sample_line) %> |
<%= link_to 'Back', sample_lines_path %>