config/routes.rb
CoolInnovations::Application.routes.draw do

  resources :stations do
    post :update_station, :on => :collection
    get :index_floor, :on => :collection
  end

  resources :attachments

  resources :part_process_categories do
    post :update_part_process_category, :on => :collection
    post :set_sort_priority, :on => :collection
  end

  resources :hardware_categories do
    post :update_hardware_category, :on => :collection
    post :set_sort_priority, :on => :collection
  end

  resources :sample_lines

  resources :comments

  resources :shipping_methods do
    get :search, :on => :collection
    post :update_shipping_method, :on => :collection
  end

  resources :order_lines do
    post :set_process_status, :on => :collection
    post :update_order_line, :on => :collection
    post :update_order_lines, :on => :collection
    post :reset_order_line_status, :on => :collection
    post :assign_user, :on => :collection
    post :update_order_line_process_status, :on => :collection
    get :accordion_details, :on => :member
  end

  resources :orders do
    match :shipped, :on => :collection, :action => :index, :display => "shipped"
    match :update_search_dropdowns, :on => :collection
  end

  resources :parts do
    get  :search, :on => :collection
    post :update_part, :on => :collection
    post :set_required_process_priority, :on => :member
    get :accordion_details, :on => :member
  end

  resources :part_processes do
    post :part_processes, :on => :collection
    post :set_order_line_priority, :on => :member
    post :reset_order_line_priority, :on => :member
    post :update_part_process, :on => :collection
    get :accordion_details, :on => :member
  end

  resources :hardwares do
    get :search, :on => :collection
    post :update_hardware, :on => :collection
    get :accordion_details, :on => :member
  end

  resources :users do
    post :update_user, :on => :collection
    post :set_process_priority, :on => :member
  end
  resources :sessions

  resources :clients do
    get :search, :on => :collection
    post :update_client, :on => :collection
    get :accordion_details, :on => :member
  end

  root to: "sessions#index"
  get 'login' => "sessions#new"
  get 'logout' => "sessions#destroy"

end

app/models/shipping_method.rb
class ShippingMethod < ActiveRecord::Base
  attr_accessible :name, :duration

                  validates_presence_of :name, :duration
  validates_uniqueness_of :name, :case_sensitive => false

  has_many :order_lines

end

app/controllers/shipping_methods_controller.rb
class ShippingMethodsController < ApplicationController
  # GET /shipping_methods
  # GET /shipping_methods.json
  def index
    @shipping_methods = ShippingMethod.order(:name).page(params[:page]).per_page(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shipping_methods }
    end
  end

  # GET /shipping_methods/1
  # GET /shipping_methods/1.json
  def show
    @shipping_method = ShippingMethod.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shipping_method }
    end
  end

  # GET /shipping_methods/new
  # GET /shipping_methods/new.json
  def new
    @shipping_method = ShippingMethod.new

    respond_to do |format|
      format.html do
        render :layout => false if params[:no_layout]
      end
      format.json { render json: @shipping_method }
    end
  end

  # GET /shipping_methods/1/edit
  def edit
    @shipping_method = ShippingMethod.find(params[:id])

    respond_to do |format|
      format.html do
        render :layout => false if params[:no_layout]
      end
      format.json { render json: @shipping_method }
    end
  end

  # POST /shipping_methods
  # POST /shipping_methods.json
  def create
    @shipping_method = ShippingMethod.new(params[:shipping_method])

    respond_to do |format|
      if @shipping_method.save
        format.html { redirect_to @shipping_method, notice: 'Shipping method was successfully created.' }
        format.js
      else
        format.html { render action: "new" }
        format.js
      end
    end
  end



  # PUT /shipping_methods/1
  # PUT /shipping_methods/1.json
  def update
    @shipping_method = ShippingMethod.find(params[:id])

    respond_to do |format|
      if @shipping_method.update_attributes(params[:shipping_method])
        format.html { redirect_to @shipping_method, notice: 'Shipping method was successfully updated.' }
        format.js
      else
        format.html { render action: "edit" }
        format.js
      end
    end
  end

  # DELETE /shipping_methods/1
  # DELETE /shipping_methods/1.json
  def destroy
    @shipping_method = ShippingMethod.find(params[:id])
    @shipping_method.destroy

    respond_to do |format|
      format.html { redirect_to shipping_methods_url }
      format.json { head :no_content }
    end
  end

  def search
    params[:shipping_method] ||= {}
    query = "%#{params[:shipping_method][:query]}%"

    @shipping_methods = ShippingMethod.where{name =~ query}.order(:name).page(params[:page]).per_page(20) if query.present?

    respond_to do |format|
      format.html { render :index}
      format.json { render json: @shipping_methods }
    end
  end

  def update_shipping_method
    @shipping_method = ShippingMethod.find(params[:id])
    @shipping_method[params[:field]] = params[:new_value]
    @shipping_method.save
  end
end

app/helpers/shipping_methods_helper.rb
module ShippingMethodsHelper
end

app/views/shipping_methods/_form.html.erb
<%= simple_form_for(@shipping_method, :remote => true, :html => { :class => 'form-horizontal' }) do |f| %>
    <%= f.error_notification %>

    <div class="modal-body">
      <%= f.input :name %>
      <%= f.input :duration, :label => "Duration (in days)" %>
    </div>

    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal">Cancel</a>
      <%= f.submit nil, :class => 'btn btn-primary' %>
    </div>
<% end %>

app/views/shipping_methods/_search_form.html.erb
<%= simple_form_for :shipping_method, :url => search_shipping_methods_path, :method => :get do |f| %>
    <%= f.error_notification %>

    <%= f.input :query,
                :label => false,
                :wrapper_html => { :class => 'pull-left mrx' },
                :placeholder => 'Search for shipping method'%>
    <%= f.submit 'Search', :class => 'btn pull-left mrx' %>
<% end %>

app/views/shipping_methods/edit.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">×</button>
  <h3>Edit Shipping Method</h3>
</div>

<%= render 'form' %>

app/views/shipping_methods/index.html.erb
<h1>Shipping Methods</h1>

<%= render 'search_form' %>
<%= link_to 'New Shipping Method', "/shipping_methods/new?no_layout=1", :class => 'btn btn-primary pull-right mrx modal-trigger'%>


<% if @shipping_methods.length > 0 %>

    <% if params.fetch(:shipping_method, {})[:query].present? %>
        <div class="row">
          <div class="span9 mbxx">
            your search for <em><strong>"<%= params[:shipping_method][:query] %>"</strong></em>  returned <strong><%= pluralize(@shipping_methods.count, 'result') %></strong>
          </div>
        </div>
    <% end %>

    <table class="table table-bordered">
      <thead>
      <tr>
        <th>Shipping Method Name</th>
        <th>Duration (in days)</th>
        <th>&nbsp;</th>
      </tr>
      </thead>
      <tbody>
      <% @shipping_methods.each do |shipping_method| %>
          <tr>
            <td class="editable large3" data-headers="/shipping_methods/update_shipping_method"  id="name-<%= shipping_method.id %>"><%= shipping_method.name %></td>
            <td class="editable large3" data-headers="/shipping_methods/update_shipping_method"  id="duration-<%= shipping_method.id %>"><%= shipping_method.duration %></td>
            <td class="actions">
              <%= link_to shipping_method, method: :delete, data: { confirm: "Are you sure you want to delete this shipping method? \n" + shipping_method.name }, :class => 'btn btn-small btn-danger', :title => 'Delete' do%>
                  <i class="icon-trash" alt="delete"></i>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <%= will_paginate @shipping_methods, :renderer => BootstrapPagination::Rails %>
<% else %>
    <div class="row">
      <div class="span9 mbxx">
        There are no results
      </div>
    </div>
<% end %>

app/views/shipping_methods/new.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">×</button>
  <h3>New Shipping Method</h3>
</div>

<%= render 'form' %>

app/views/shipping_methods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @shipping_method.name %>
</p>

<p>
  <b>Duration:</b>
  <%= @shipping_method.duration %>
</p>


<%= link_to 'Edit', edit_shipping_method_path(@shipping_method) %> |
<%= link_to 'Back', shipping_methods_path %>