config/routes.rb
CoolInnovations::Application.routes.draw do

  resources :stations do
    post :update_station, :on => :collection
    get :index_floor, :on => :collection
  end

  resources :attachments

  resources :part_process_categories do
    post :update_part_process_category, :on => :collection
    post :set_sort_priority, :on => :collection
  end

  resources :hardware_categories do
    post :update_hardware_category, :on => :collection
    post :set_sort_priority, :on => :collection
  end

  resources :sample_lines

  resources :comments

  resources :shipping_methods do
    get :search, :on => :collection
    post :update_shipping_method, :on => :collection
  end

  resources :order_lines do
    post :set_process_status, :on => :collection
    post :update_order_line, :on => :collection
    post :update_order_lines, :on => :collection
    post :reset_order_line_status, :on => :collection
    post :assign_user, :on => :collection
    post :update_order_line_process_status, :on => :collection
    get :accordion_details, :on => :member
  end

  resources :orders do
    match :shipped, :on => :collection, :action => :index, :display => "shipped"
    match :update_search_dropdowns, :on => :collection
  end

  resources :parts do
    get  :search, :on => :collection
    post :update_part, :on => :collection
    post :set_required_process_priority, :on => :member
    get :accordion_details, :on => :member
  end

  resources :part_processes do
    post :part_processes, :on => :collection
    post :set_order_line_priority, :on => :member
    post :reset_order_line_priority, :on => :member
    post :update_part_process, :on => :collection
    get :accordion_details, :on => :member
  end

  resources :hardwares do
    get :search, :on => :collection
    post :update_hardware, :on => :collection
    get :accordion_details, :on => :member
  end

  resources :users do
    post :update_user, :on => :collection
    post :set_process_priority, :on => :member
  end
  resources :sessions

  resources :clients do
    get :search, :on => :collection
    post :update_client, :on => :collection
    get :accordion_details, :on => :member
  end

  root to: "sessions#index"
  get 'login' => "sessions#new"
  get 'logout' => "sessions#destroy"

end

app/models/order_line.rb
class OrderLine < ActiveRecord::Base
  STATUSES = [
    "pending",
    "assigned",
    "in progress",
    "completed",
    "verified"
  ]

  FLOOR_STATUSES = [
      "assigned",
      "in progress",
      "completed"
  ]

  COLORS = [
      "a-green",
      "b-red",
      "c-yellow",
      "d-orange",
      "e-purple",
      "f-white"
  ]

  attr_accessible :due_date, :ship_date, :order_id, :part_id, :quantity, :comment, :price, :setup_cost, :shipping_method_id, :line_number, :breakdown, :tracking_number, :_destroy

  validates_presence_of :due_date, :part_id, :quantity

  belongs_to :order
  belongs_to :part
  belongs_to :shipping_method

  has_many :order_line_process_statuses, :dependent => :destroy

  after_create :build_statuses

  after_destroy :check_order

  # track only due date changes
  has_paper_trail :only => [:due_date]

  def self.shipped
    where { status == "shipped" }
  end

  def self.not_shipped
    where { status != "shipped" }
  end

  def self.pending
    where { (status == "assigned") | (status == "in progress") | (status == "pending") }
  end

  def process_statuses
    self.order_line_process_statuses.joins(:order_line).joins("INNER JOIN required_processes ON required_processes.part_process_id = order_line_process_statuses.part_process_id AND required_processes.part_id = order_lines.part_id").order("required_processes.required_process_priority asc")
  end

  # shipped => true | false
  # client_id => 
  # order_id => 
  # params => 
  # sort =>
  # page =>
  # per_page =>
  def self.search(options = {})
    order_lines = OrderLine.joins(:order => :client).includes(:order => :client).includes(:part).joins(:part)
    order_lines = options[:shipped] ? order_lines.shipped : order_lines.not_shipped
    order_lines = order_lines.where{clients.id == options[:client_id]} if options[:client_id].present?
    order_lines = order_lines.where{orders.id == options[:order_id]} if options[:order_id].present?

    if options[:status_option].present?
      case options[:status_option]
      when 0, "0"
        order_lines = order_lines.where{status != "completed"}
      when 1, "1"
        order_lines = order_lines.where(:status => "completed")
      end
    end
    if options[:start_date].present?
      begin
        Date.parse(options[:start_date])
        order_lines = options[:shipped] ? order_lines.where{actual_ship_date >= options[:start_date]} : order_lines.where{created_at >= options[:start_date].to_date}
      rescue
      end
    end
    if options[:end_date].present?
      begin
        Date.parse(options[:end_date])
        order_lines = options[:shipped] ? order_lines.where{actual_ship_date <= options[:end_date].to_date} : order_lines.where{created_at <= options[:end_date].to_date.end_of_day}
      rescue
      end
    end

    order_lines = order_lines.where(options[:search]) if options[:search].present?

    if options[:sort] =~ /^color/
      options[:sort] = "color ASC, ship_date ASC, clients.name ASC"
    end

    order_lines = order_lines.order(options[:sort]).page(options[:page] || 1).per_page(options[:per_page] || 10)
  end



  private

  def build_statuses
    self.part.part_processes.each do |process|
      status = self.order_line_process_statuses.new(
        :status => "pending"
      )
      status.part_process_id = process.id
      status.save
    end
  end

  # check if order should be deleted
  def check_order
    if order.order_lines.count == 0
      order.destroy
    end
  end


end

app/controllers/order_lines_controller.rb
class OrderLinesController < ApplicationController
  # GET /order_lines
  # GET /order_lines.json
  def index
    @order_lines = OrderLine.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @order_lines }
    end
  end

  # GET /order_lines/1
  # GET /order_lines/1.json
  def show
    @order_line = OrderLine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order_line }
    end
  end

  # GET /order_lines/new
  # GET /order_lines/new.json
  def new
    @order_line = OrderLine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order_line }
    end
  end

  # GET /order_lines/1/edit
  def edit
    @order_line = OrderLine.find(params[:id])
  end

  # POST /order_lines
  # POST /order_lines.json
  def create
    @order_line = OrderLine.new(params[:order_line])

    respond_to do |format|
      if @order_line.save
        format.html { redirect_to @order_line, notice: 'Order line was successfully created.' }
        format.json { render json: @order_line, status: :created, location: @order_line }
      else
        format.html { render action: "new" }
        format.json { render json: @order_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /order_lines/1
  # PUT /order_lines/1.json
  def update
    @order_line = OrderLine.find(params[:id])

    respond_to do |format|
      if @order_line.update_attributes(params[:order_line])
        format.html { redirect_to @order_line, notice: 'Order line was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_lines/1
  # DELETE /order_lines/1.json
  def destroy
    @order_line = OrderLine.find(params[:id])
    @order_line.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  def set_process_status
    @order_line_process_status = OrderLineProcessStatus.find(params[:order_line_process_status_id])
    @order_line_process_status.status = params[:status]
    if params[:status] == 'pending'
      @order_line_process_status.user_id = 0
    end
    @order_line_process_status.save
  end

  def update_order_line
    @order_line = OrderLine.find(params[:id])


    if params[:field] == "created_at" or params[:field] == "actual_ship_date" or params[:field] == "due_date" or params[:field] == "ship_date"
      @order_line[params[:field]] = Date.strptime(params[:new_value], "%m/%d/%y") + 1.hour
    else
      @order_line[params[:field]] = params[:new_value]
    end

    @order_line.save
  end

  def update_order_lines
    @changedField = params[:field]
    params[:ids] ||= []
    params[:ids].each do |id|
      @order_line = OrderLine.find(id)
      @order_line[params[:field]] = params[:value]
      if params[:field] == "status" && params[:value] == "shipped"
        @order_line.actual_ship_date = Time.now
      end
      @order_line.save
    end
  end

  def reset_order_line_status
    @order_line = OrderLine.find(params[:id])
    @order_line.status = "completed"
    @order_line.save
  end

  def accordion_details
    @users = User.users_only
    @order_line = OrderLine.find(params[:id])
    render :partial => 'order_lines/accordion_details', :locals => {:order_line => @order_line }
  end

  def assign_user
    @order_line_process_status = OrderLineProcessStatus.find(params[:order_line_process_status_id])
    @order_line_process_status.user_id = params[:user_id]
    current_status = params[:user_id].to_i == 0 ? "pending" : "assigned"
    @order_line_process_status.status = current_status
    @order_line_process_status.save
  end

  def update_order_line_process_status
    @order_line_process_status = OrderLineProcessStatus.find(params[:id])
    @order_line_process_status[params[:field]] = params[:new_value]
    @order_line_process_status.save
  end
end

app/helpers/order_lines_helper.rb
module OrderLinesHelper
end

app/views/order_lines/_accordion.html.erb
<tr>
  <td colspan="<%= colspan %>" class="order-line-info hide">
    <div class="accordion-body collapse" id="collapse<%= order_line.id %>" data-headers="/order_lines/<%= order_line.id %>/accordion_details">
      <!--<h4>Order line details</h4>-->
      <%# render :partial => 'order_lines/_accordion_details', :locals => { :order_line => order_line } %>
    </div>
  </td>
</tr>

app/views/order_lines/_accordion_details.html.erb
<div class="span10">
  <h5>Process</h5>
  <table class="table table-bordered table-condensed span9">
    <tr>
      <th>Process Name</th>
      <th>Status</th>
      <th>Assign</th>
    </tr>
    <% order_line.process_statuses.each do |process_status| %>
      <% if process_status.part_process %>
        <tr class="process_status" data-id="<%= process_status.id %>">
          <td class="span2"><%= process_status.part_process.name %></td>
          <td class="process-statuses">
            <div class="btn-group line-status" data-toggle="buttons-radio">
              <% OrderLine::STATUSES.each do |order_line_status| %>
                <% extra_class = "" %>
                <% if order_line_status == process_status.status %>
                  <% extra_class = "active" %>
                  <% if process_status.status == "pending" %>
                    <% extra_class = extra_class + " btn-warning" %>
                  <% end %>
                  <% if process_status.status == "assigned" %>
                      <% extra_class = extra_class + " btn-danger" %>
                  <% end %>
                  <% if process_status.status == "in progress" %>
                    <% extra_class = extra_class + " btn-info" %>
                  <% end %>
                  <% if process_status.status == "completed" %>
                    <% extra_class = extra_class + " btn-success" %>
                  <% end %>
                  <% if process_status.status == "verified" %>
                      <% extra_class = extra_class + " btn-primary" %>
                  <% end %>
                <% end %>
                <button class="btn btn-small <%= extra_class %>"  data-value="<%= order_line_status %>"><%= order_line_status %></button>
              <% end %>
            </div>
          </td>
          <td class="assigned-users" data-id="<%= process_status.id %>">
            <select class="assign-user span3">
              <option value="0">Not Assigned</option>
              <% @users.each do |user| %>
                  <option <% if (process_status.user_id == user.id)%>selected="selected"<%end%> value="<%= user.id %>"><%= user.name %></option>
              <% end %>
            </select>
          </td>
        </tr>
      <% end%>
    <% end %>
  </table>
</div>
<div class="span5">
  <h5>Hardware</h5>
  <table class="table table-bordered table-condensed span5 table-striped">
    <tr>
      <th>Hardware Name</th>
      <th>Part Qty</th>
      <th>Order Qty</th>
    </tr>
    <% order_line.part.required_hardwares.each do |hardware| %>
      <tr>
        <td><%= hardware.hardware.name %></td>
        <td><%= hardware.quantity %></td>
        <td><%= hardware.quantity * order_line.quantity %></td>
      </tr>
    <% end %>
  </table>
  <h5>Additional Info</h5>
  <table class="table table-bordered table-condensed table-striped">
    <% if order_line.order.attachment? or order_line.part.attachments.present? or order_line.part.description? or order_line.order.client.payment_instructions? or order_line.order.client.shipping_instructions? or order_line.order.client.special_instructions? %>
        <% if manager_or_admin? %>
          <% order_line.order.attachments.each do |attachment| %>
              <tr>
                <td class="span2"><strong>Order Attachment:</strong></td>
                <td><%= link_to attachment.name, attachment.file.url , :target => "_blank" %></td>
              </tr>
          <% end %>
        <% end %>
        <% if order_line.part.attachments.present? %>
            <tr>
              <td class="span2"><strong>Part Drawing:</strong></td>
              <td>
                <% order_line.part.attachments.each do |attachment| %>
                    <div>
                      <%= link_to attachment.name, attachment.file.url , :target => "_blank" %>
                    </div>
                <% end %>
              </td>
            </tr>
        <% end %>
        <% if order_line.part.description? %>
            <tr>
              <td class="span2"><strong>Part Comment:</strong></td>
              <td><%= order_line.part.description %></td>
            </tr>
        <% end %>
        <% if order_line.order.client.payment_instructions?  %>
            <tr>
              <td class="span2"><strong>Payment Instructions:</strong></td>
              <td><%= order_line.order.client.payment_instructions %></td>
            </tr>
        <% end %>
        <% if order_line.order.client.shipping_instructions?  %>
            <tr>
              <td class="span2"><strong>Shipping Instructions:</strong></td>
              <td><%= order_line.order.client.shipping_instructions %></td>
            </tr>
        <% end %>
        <% if order_line.order.client.special_instructions?  %>
            <tr>
              <td class="span2"><strong>Special Instructions:</strong></td>
              <td><%= order_line.order.client.special_instructions %></td>
            </tr>
        <% end %>
    <% else %>
        <tr>
          <td>No special instructions</td>
        </tr>
    <% end %>
  </table>
  <% if order_line.versions.count > 1 %>
      <h5>Date changes</h5>
      <table class="table table-bordered table-condensed span5 table-striped">
        <tr>
          <th>Changed on</th>
          <th>By</th>
          <th>Old Value</th>
        </tr>
        <% order_line.versions.order("created_at desc").limit(5).each_with_index do |version,i| %>
            <% if i>0 %>
                <tr>
                  <td><%= version.created_at.to_s(:long) %></td>
                  <td><%= User.find_by_id(version.whodunnit).try(:username) %></td>
                  <td><%= version.reify.try(:due_date) %></td>
                </tr>
            <% end %>
        <% end %>
      </table>
  <% end %>
</div>

app/views/order_lines/_form.html.erb
<%= simple_form_for(@order_line, :html => { :class => 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :order_id %>
    <%= f.input :part_id %>
    <%= f.input :due_date %>
    <%= f.input :quantity %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to 'Cancel', order_lines_path, :class => 'btn' %>
  </div>
<% end %>

app/views/order_lines/_no_orders.html.erb
<% colspan = 10 %>
<% if local_assigns[:show_client].present? %>
    <% colspan = 11 %>
<% end %>
<tr>
  <td colspan="<%= colspan %>">There are no order lines</td>
</tr>

app/views/order_lines/_order_line.html.erb
<% colspan = 9 %>
<% if params["display"] == "shipped" %>
    <% colspan = colspan - 1 %>
<% end %>

<% extraClass = '' %>
<% if params["display"] != "shipped" %>
    <% extraClass = order_line.color %>
<% end %>

<tr class="order_line <%= extraClass %>" data-id="<%= order_line.id %>">
  <% if @process_order_line_priority %>
    <td class="fixed sort_handle"><%= order_line.order_line_process_statuses.where(:part_process_id => @process_order_line_priority).first.order_line_priority %></td>
  <% end %>
  <% if params["display"] != "shipped" %>
      <td class="fixed editable comment" id="created_at-<%= order_line.id%>" data-headers="/order_lines/update_order_line" data-content="<%= display_date(order_line.created_at) %>"><%= display_date(order_line.created_at) %></td>
  <% end %>
  <% if local_assigns[:show_client].present? %>
    <% colspan += 1 %>
    <% if params["display"] != "shipped" %>
        <td class="fixed"><a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse<%= order_line.id %>"><i class="icon-plus"></i> <%= order_line.order.client.name %></a></td>
    <% else %>
          <td class="fixed"><%= order_line.order.client.name %></td>
    <% end %>
    <td class="fixed"><%= order_line.order.purchase_order %></td>
  <% else %>
      <td class="fixed"><a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse<%= order_line.id %>"><i class="icon-plus"></i> <%= order_line.order.purchase_order %></a></td>
  <% end %>
  <td class="fixed"><%= order_line.line_number %></td>
  <td class="fixed"><%= order_line.part.name.upcase %></td>
  <td class="editable qty" data-headers="/order_lines/update_order_line" id="quantity-<%= order_line.id%>"><%= order_line.quantity %></td>
  <% if params["display"] == "shipped" %>
    <td class="editable comment" data-headers="/order_lines/update_order_line" id="actual_ship_date-<%= order_line.id%>"><%= display_date(order_line.actual_ship_date) %></td>
  <% else %>
    <td class="fixed editable comment" id="ship_date-<%= order_line.id%>" data-headers="/order_lines/update_order_line" data-content="<%= display_date(order_line.ship_date) %>"><%= display_date(order_line.ship_date) %></td>
  <% end %>
  <td class="fixed editable comment" id="due_date-<%= order_line.id%>" data-headers="/order_lines/update_order_line" data-content="<%= display_date(order_line.due_date) %>"><%= display_date(order_line.due_date) %></td>
  <td class="editable large" data-headers="/order_lines/update_order_line"  id="comment-<%= order_line.id%>" data-content="<%= order_line.comment %>" data-substr="20"><%= truncate(order_line.comment, :length => 20) %></td>
  <% if params["display"] == "shipped" %>
    <td class="fixed editable comment" data-headers="/order_lines/update_order_line"  id="tracking_number-<%= order_line.id%>"><%= order_line.tracking_number %></td>
  <% end %>
  <td class="actions <% if params["display"] == "shipped" %>small<% end %> fixed <%= order_line.status.gsub(/\s+/, '-') %>">
    <span class="status btn btn-small" title="<%= order_line.status %>"><i class="icon-star-empty"></i></span>
    <% if params["display"] != "shipped" %>
        <%= link_to edit_order_path(order_line.order), :class => 'btn btn-small', :title => 'Edit' do%>
            <i class="icon-edit"></i>
        <% end %>
    <% end %>
    <%= link_to order_line, method: :delete, data: { confirm: "Are you sure? \n P/O #:" + order_line.order.purchase_order + "\nCustomer:" + order_line.order.client.name }, :class => 'btn btn-small btn-danger', :title => 'Delete' do%>
        <i class="icon-trash" alt="delete"></i>
    <% end %>
    <% if params["display"] != "shipped" %>
        <% if local_assigns[:show_client].present? %>
            <input type="checkbox" name="ship-order-lines" class="ship-lines" value="ol-<%= order_line.id%>">
        <% end %>
    <% else %>
        <a href="#" data-id="<%= order_line.id %>" class="btn btn-warning btn-small unship" title="Unship"><i class="icon-repeat" alt="Roll back"></i></a>
    <% end %>
  </td>
</tr>
<% if params["display"] != "shipped" %>
  <%= render :partial => 'order_lines/accordion', :locals => {:order_line => order_line, :colspan => colspan} %>
<% end %>

app/views/order_lines/_order_line_simple.html.erb
<tr class="order_line"  data-id="<%= order_line.id %>">
  <% if @process_order_line_priority %>
      <td class="fixed sort_handle"><%= order_line_counter + 1%></td>
  <% end %>
  <% if order_line.order.nil? %>
    <td colspan="2">Order not found.</td>
  <% else %>
    <td><%= order_line.order.purchase_order %></td>
    <td><% if order_line.order.client %><%= order_line.order.client.name %><% end %></td>
  <% end %>
  <td><% if order_line.part %><%= order_line.part.name.upcase %><% end %></td>
  <td><%= number_with_delimiter(order_line.quantity) %></td>
  <% if view == 'hardware' %>
    <td><%= number_with_delimiter(order_line.part.required_hardwares.where(:hardware_id => hardware.id)[0].quantity * order_line.quantity) %></td>
  <% end %>
  <td><%= order_line.ship_date %></td>
  <td><%= order_line.due_date %></td>
  <% if view == "part_process" %>
    <% order_line_process_status = order_line.order_line_process_statuses.detect{|x| x.part_process_id == part_process.id} %>
    <td><%= order_line_process_status.status %></td>
    <td data-id="<%= order_line_process_status.id%>">
      <select class="assign-user span3">
        <option value="0">Not Assigned</option>
        <% @users.each do |user| %>
            <option <% if (order_line_process_status.user_id == user.id)%>selected="selected"<%end%>  value="<%= user.id %>"><%= user.name %></option>
        <% end %>
      </select>
    </td>

  <% end %>
</tr>

app/views/order_lines/edit.html.erb
<h1>Editing order_line</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_line %> |
<%= link_to 'Back', order_lines_path %>

app/views/order_lines/index.html.erb
<h1>Listing order_lines</h1>

<table class="table table-striped">
  <tr>
    <th>Order</th>
    <th>Part</th>
    <th>Dock date</th>
    <th>Quantity</th>
    <th>Actions</th>
  </tr>

<% @order_lines.each do |order_line| %>
  <tr>
    <td><%= order_line.order_id %></td>
    <td><%= order_line.part_id %></td>
    <td><%= order_line.due_date %></td>
    <td><%= order_line.quantity %></td>
    <td>
      <%= link_to 'Show', order_line, :class => 'btn btn-mini' %>
      <%= link_to 'Edit', edit_order_line_path(order_line), :class => 'btn btn-mini' %>
      <%= link_to 'Destroy', order_line, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order line', new_order_line_path, :class => 'btn btn-primary' %>

app/views/order_lines/new.html.erb
<h1>New order_line</h1>

<%= render 'form' %>

<%= link_to 'Back', order_lines_path %>

app/views/order_lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Order:</b>
  <%= @order_line.order_id %>
</p>

<p>
  <b>Part:</b>
  <%= @order_line.part_id %>
</p>

<p>
  <b>Dock date:</b>
  <%= @order_line.due_date %>
</p>

<p>
  <b>Quantity:</b>
  <%= @order_line.quantity %>
</p>


<%= link_to 'Edit', edit_order_line_path(@order_line) %> |
<%= link_to 'Back', order_lines_path %>